// Universities
export const ADD_UNIVERSITY = 'ADD_UNIVERSITY';
export const RECEIVE_UNIVERSITIES = 'RECEIVE_UNIVERSITIES';

// Toast
export const SHOW_TOAST_MESSAGE = 'SHOW_TOAST_MESSAGE';
export const CLOSE_TOAST_MESSAGE = 'CLOSE_TOAST_MESSAGE';
